// Generated by gencpp from file ifm3d/SyncClocks.msg
// DO NOT EDIT!


#ifndef IFM3D_MESSAGE_SYNCCLOCKS_H
#define IFM3D_MESSAGE_SYNCCLOCKS_H

#include <ros/service_traits.h>


#include <ifm3d/SyncClocksRequest.h>
#include <ifm3d/SyncClocksResponse.h>


namespace ifm3d
{

struct SyncClocks
{

typedef SyncClocksRequest Request;
typedef SyncClocksResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SyncClocks
} // namespace ifm3d


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ifm3d::SyncClocks > {
  static const char* value()
  {
    return "e50a755d48be526edaee6d407b363d64";
  }

  static const char* value(const ::ifm3d::SyncClocks&) { return value(); }
};

template<>
struct DataType< ::ifm3d::SyncClocks > {
  static const char* value()
  {
    return "ifm3d/SyncClocks";
  }

  static const char* value(const ::ifm3d::SyncClocks&) { return value(); }
};


// service_traits::MD5Sum< ::ifm3d::SyncClocksRequest> should match 
// service_traits::MD5Sum< ::ifm3d::SyncClocks > 
template<>
struct MD5Sum< ::ifm3d::SyncClocksRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ifm3d::SyncClocks >::value();
  }
  static const char* value(const ::ifm3d::SyncClocksRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ifm3d::SyncClocksRequest> should match 
// service_traits::DataType< ::ifm3d::SyncClocks > 
template<>
struct DataType< ::ifm3d::SyncClocksRequest>
{
  static const char* value()
  {
    return DataType< ::ifm3d::SyncClocks >::value();
  }
  static const char* value(const ::ifm3d::SyncClocksRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ifm3d::SyncClocksResponse> should match 
// service_traits::MD5Sum< ::ifm3d::SyncClocks > 
template<>
struct MD5Sum< ::ifm3d::SyncClocksResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ifm3d::SyncClocks >::value();
  }
  static const char* value(const ::ifm3d::SyncClocksResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ifm3d::SyncClocksResponse> should match 
// service_traits::DataType< ::ifm3d::SyncClocks > 
template<>
struct DataType< ::ifm3d::SyncClocksResponse>
{
  static const char* value()
  {
    return DataType< ::ifm3d::SyncClocks >::value();
  }
  static const char* value(const ::ifm3d::SyncClocksResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IFM3D_MESSAGE_SYNCCLOCKS_H
